name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ planner ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
        golangci-lint run --config .golangci.yml ./...
        
    - name: Test
      run: go test -race -count=100 ./...
      
    - name: Build
      run: go build -o financial_planner